// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://umvhwbshppchbkgqhepk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVtdmh3YnNocHBjaGJrZ3FoZXBrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3NzIyNzgsImV4cCI6MjA2ODM0ODI3OH0.OtMUNJ7jCGVKi3AV_HRlSJy1GhdXaE1qx0B8P9q9AQA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});